export const dummyData = [
    {
        groupName: 'softdrinks',
        itemName: 'Coke Kasalo',
        retailPrice: 32,
        wholesalePrice: 281,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Coke 8oz',
        retailPrice: 13,
        wholesalePrice: 186,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Coke Mismo',
        retailPrice: 20,
        wholesalePrice: 205,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Coke Swakto',
        retailPrice: 15,
        wholesalePrice: 150,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'RC Mega',
        retailPrice: 28,
        wholesalePrice: 250,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'RC 8oz',
        retailPrice: 12,
        wholesalePrice: 175,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'RC Mismo',
        retailPrice: 0,
        wholesalePrice: 0,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Mountain Dew Mismo',
        retailPrice: 20,
        wholesalePrice: 205,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Cobra',
        retailPrice: 20,
        wholesalePrice: 205,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Cobra Plastic',
        retailPrice: 20,
        wholesalePrice: 205,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Sting',
        retailPrice: 20,
        wholesalePrice: 205,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Sting Plastic',
        retailPrice: 20,
        wholesalePrice: 205,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Mineral',
        retailPrice: 15,
        wholesalePrice: 15,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
    {
        groupName: 'softdrinks',
        itemName: 'Wilkins 8 liter',
        retailPrice: 95,
        wholesalePrice: 0,
        basePrice: 0,
        id: crypto.randomUUID(),
    },
]
